#!/bin/bash
FILE=cpu
make $FILE
if test -f "./$FILE"; then
    S1="./cfg/cpu.cfg"
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE $S1
fi