#!/bin/bash
FILE=kernel
make $FILE
if test -f "./$FILE"; then
    S1="./cfg/deadlock"
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=no --show-reachable=no --num-callers=20 ./$FILE $S1
fi